name: phenoplier_light
channels:
  - conda-forge
dependencies:
  - ipython
  - numpy=1.19.*
  - pandas=1.1.*
  - pip
  - python=3.8.*
  - pyyaml=5.3.*
  - r-base=3.6.*
  - r-essentials
  - scikit-learn=0.23.*
  - scipy=1.5.*
